<?php
function cpm_register_post_types() {
    $labels = array(
        'name'                  => _x('Patients', 'Post Type General Name', 'text_domain'),
        'singular_name'         => _x('Patient', 'Post Type Singular Name', 'text_domain'),
        'menu_name'             => __('Patients', 'text_domain'),
        'name_admin_bar'        => __('Patient', 'text_domain'),
        'archives'              => __('Patient Archives', 'text_domain'),
        'attributes'            => __('Patient Attributes', 'text_domain'),
        'parent_item_colon'     => __('Parent Patient:', 'text_domain'),
        'all_items'             => __('All Patients', 'text_domain'),
        'add_new_item'          => __('Add New Patient', 'text_domain'),
        'add_new'               => __('Add New', 'text_domain'),
        'new_item'              => __('New Patient', 'text_domain'),
        'edit_item'             => __('Edit Patient', 'text_domain'),
        'update_item'           => __('Update Patient', 'text_domain'),
        'view_item'             => __('View Patient', 'text_domain'),
        'view_items'            => __('View Patients', 'text_domain'),
        'search_items'          => __('Search Patient', 'text_domain'),
        'not_found'             => __('Not found', 'text_domain'),
        'not_found_in_trash'    => __('Not found in Trash', 'text_domain'),
        'featured_image'        => __('Featured Image', 'text_domain'),
        'set_featured_image'    => __('Set featured image', 'text_domain'),
        'remove_featured_image' => __('Remove featured image', 'text_domain'),
        'use_featured_image'    => __('Use as featured image', 'text_domain'),
        'insert_into_item'      => __('Insert into patient', 'text_domain'),
        'uploaded_to_this_item' => __('Uploaded to this patient', 'text_domain'),
        'items_list'            => __('Patients list', 'text_domain'),
        'items_list_navigation' => __('Patients list navigation', 'text_domain'),
        'filter_items_list'     => __('Filter patients list', 'text_domain'),
    );
    $args = array(
        'label'                 => __('Patient', 'text_domain'),
        'description'           => __('Post Type for managing patients', 'text_domain'),
        'labels'                => $labels,
        'supports'              => array('title'),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 5,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
    );
    register_post_type('patient', $args);

    // Register Visit CPT
    $visit_labels = array(
        'name'                  => _x('Visits', 'Post Type General Name', 'text_domain'),
        'singular_name'         => _x('Visit', 'Post Type Singular Name', 'text_domain'),
        'menu_name'             => __('Visits', 'text_domain'),
        'name_admin_bar'        => __('Visit', 'text_domain'),
        'archives'              => __('Visit Archives', 'text_domain'),
        'attributes'            => __('Visit Attributes', 'text_domain'),
        'parent_item_colon'     => __('Parent Visit:', 'text_domain'),
        'all_items'             => __('All Visits', 'text_domain'),
        'add_new_item'          => __('Add New Visit', 'text_domain'),
        'add_new'               => __('Add New', 'text_domain'),
        'new_item'              => __('New Visit', 'text_domain'),
        'edit_item'             => __('Edit Visit', 'text_domain'),
        'update_item'           => __('Update Visit', 'text_domain'),
        'view_item'             => __('View Visit', 'text_domain'),
        'view_items'            => __('View Visits', 'text_domain'),
        'search_items'          => __('Search Visit', 'text_domain'),
        'not_found'             => __('Not found', 'text_domain'),
        'not_found_in_trash'    => __('Not found in Trash', 'text_domain'),
        'featured_image'        => __('Featured Image', 'text_domain'),
        'set_featured_image'    => __('Set featured image', 'text_domain'),
        'remove_featured_image' => __('Remove featured image', 'text_domain'),
        'use_featured_image'    => __('Use as featured image', 'text_domain'),
        'insert_into_item'      => __('Insert into visit', 'text_domain'),
        'uploaded_to_this_item' => __('Uploaded to this visit', 'text_domain'),
        'items_list'            => __('Visits list', 'text_domain'),
        'items_list_navigation' => __('Visits list navigation', 'text_domain'),
        'filter_items_list'     => __('Filter visits list', 'text_domain'),
    );
    $visit_args = array(
        'label'                 => __('Visit', 'text_domain'),
        'description'           => __('Post Type for managing visits', 'text_domain'),
        'labels'                => $visit_labels,
        'supports'              => array('title'),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 6,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
    );
    register_post_type('visit', $visit_args);
}
add_action('init', 'cpm_register_post_types');
